Feat/fid 35/logique qr code
FideCly/api pull request #131
Opened 2022-09-13 18:59 UTC by AndiManLu

### Changes proposed in this pull request

Ajout de la logique QR Code

A tester sur Postman, les principales routes sont faites 

[FID-]

2022-09-14 08:30 UTC, sihamais requested changes
Plusieurs points à corriger : 
- Lis le Readme, t'es censé linter et formatter avant de push
- T'a pas fait de tests, c'est obligatoire
- Il y a deux migrations, une à la racine de `src` et une dans le dossier migrations. Elle doit être dans le dossier migration uniquement et avoir un nom valide qui décrit ce que ça fait genre 'CreatePromotionTable` ou `AddPromotionToCard`
- Les conventions de nommage sont pas respectées et le ticket jira est pas lié à la PR, va voir la doc sur Notion

Je reviewerai le code quand ces points sont corrigés parce que de mon coté le code est difficile à lire sans le formattage

2022-09-20 08:51 UTC, AndiManLu commented
> Plusieurs points à corriger :
> 
> * Lis le Readme, t'es censé linter et formatter avant de push
> * T'a pas fait de tests, c'est obligatoire
> * Il y a deux migrations, une à la racine de `src` et une dans le dossier migrations. Elle doit être dans le dossier migration uniquement et avoir un nom valide qui décrit ce que ça fait genre `CreatePromotionTable` ou `AddPromotionToCard`
> * Les conventions de nommage sont pas respectées et le ticket jira est pas lié à la PR, va voir la doc sur Notion
> 
> Je reviewerai le code quand ces points sont corrigés parce que de mon coté le code est difficile à lire sans le formattage


re: 
Je ferai le le formatage du code ce soir.

- Les test unitaires j’en ai jamais fait et je ne pense pas avoir le temps de voir comment ça fonctionne.

- Les migrations c’est également nouveau pour moi, mais on pourra voir ça à la réunion.

2022-10-15 12:15 UTC, sihamais requested changes
Plusieurs points à corriger :
- Renommer la PR suivant les conventions de nommage
- Lier le ticket JIRA dans la description de la PR et décrire ce qui a été fait dans cette PR
- Corriger toutes les erreurs qui ont été remontée
- Créer des tickets JIRA pour tout ce qui manque dans ce code (les tests appronfondis, les méthodes, ...)
- Faire un git pull et résoudre tout les conflits, fallait le faire plus tot il ya plein de méthodes qui ont été rajoutées pour rien parce qu'elles existent déja et les checks sont même pas lancés donc on peut pas voir si ça passe ou pas

2022-10-15 12:15 UTC, sihamais commented on src/routes/promotion.routes.ts
> +// get one shop
Commentaire faux

2022-10-15 12:15 UTC, sihamais commented on src/routes/promotion.routes.ts
> +// create a shop
Commentaire faux

2022-10-15 12:15 UTC, sihamais commented on src/routes/promotion.routes.ts
> +// update a shop
Commentaire faux

2022-10-15 12:15 UTC, sihamais commented on src/routes/promotion.routes.ts
> +// delete a shop
Commentaire faux

2022-10-15 12:15 UTC, sihamais commented on src/routes/shop.routes.ts
> +
Cette méthode existe déja... https://github.com/FideCly/api/blob/b5dd2bc8a5a1058b0f829d5f3b66d897649e2c62/src/routes/shop.routes.ts#L7
C'est un doublon
Faut penser à pull de main de temps en temps

2022-10-15 12:15 UTC, sihamais commented on src/shared/enums/type-promotion.ts
> +  PASSAGE = 1, // Number of time the customer pass in the shop
```suggestion
  CHECKOUT = 1, // Counter of a customer's checkouts
```

2022-10-19 18:15 UTC, AndiManLu commented on src/entities/promotion.ts
> +
done

2022-10-19 18:16 UTC, AndiManLu commented on src/entities/promotion.ts
> +  endAt!: Date;
done

2022-10-19 18:17 UTC, AndiManLu commented on src/controllers/promotion-counter.controller.ts
> +          promotionCounter.increment += 1;
Laissons comme ca pour l'instant, car c'est flou dans pas mal de tete en ce moment, on présentera le mode 'passage' pour la demo

2022-10-19 18:18 UTC, AndiManLu commented on src/controllers/promotion-counter.controller.ts
> +  };
done

2022-10-19 18:19 UTC, AndiManLu commented on src/controllers/promotion-counter.controller.ts
> +      res.status(201).send({ message: "Promotion created" });
???

2022-10-19 18:23 UTC, AndiManLu commented on src/controllers/promotion-counter.controller.ts
> +      res.status(400).send({ message: "Any data found in the request body" });
Je ne vois pas de pb avec le message, pour le fait que ca soit gerer avec les validators c'est ok. (mais ca peut rester, ca fait un check en plus)

2022-10-19 18:24 UTC, AndiManLu commented on src/controllers/promotion-counter.controller.ts
> +  };
- OneByUser c'est pour l'appli mobile, quand l'user voudra voir le nombre de passage qu'il a accumulé

- OneByClient c'est pour le dashboard (client)

2022-10-19 18:24 UTC, AndiManLu commented on src/controllers/promotion-counter.controller.ts
> +  };
J'ai légèrement modif la fonction et la route associée

2022-10-19 19:39 UTC, AndiManLu commented on src/controllers/promotion.controller.ts
> +}
done

2022-10-19 19:41 UTC, AndiManLu commented on src/migrations/1662740365310-test.ts
> +}
Comprends pas grand chose de vos migrations ... si tu peux fais le, sinon je vais voir ca demain avec Jeremy

2022-10-19 19:42 UTC, AndiManLu commented on src/payloads/promotion.payload.ts
> +  type?: number;
done

2022-10-19 19:43 UTC, AndiManLu commented on src/payloads/promotion.payload.ts
> +  limitAmout?: number; // Number of item in case of AMOUNT type
done

2022-10-19 19:44 UTC, AndiManLu commented on src/repositories/promotion-counter.repository.ts
> +      );
plus tard, ca marche, on verra le soucis de lisibilty après

2022-10-19 19:44 UTC, AndiManLu commented on src/repositories/promotion-counter.repository.ts
> +      );
plus tard, pas le temps

2022-10-19 19:47 UTC, AndiManLu commented on src/controllers/card.controller.ts
> +    card.endAt = payload.endAt ? new Date(payload.endAt) : new Date();
J'ai pas dev ce controller, je te le retourne donc à toi.

2022-10-19 20:43 UTC, AndiManLu commented on src/routes/promotion-counter.routes.ts
> +PromotionCounterRouter.put("/client", PromotionCounterController.update);
done

2022-12-15 10:40 UTC, closed without merging